language: node_js
node_js: --lts
before_script:
  - git config user.name "Moren YANG"
  - git config user.email "morenyang88@gmail.com"
  - sed -i'' "s~https://github.com/morenyang/blog.git~https://${GITHUB_ACCESS_TOKEN}@github.com/morenyang/blog.git~" _config.yml
script:
  - hexo g
  - hexo d
