# site
favicon: http://obtkzjq1l.bkt.clouddn.com/static/img/favicon.png

# header
## if you want to use a photo as header's background image, just type the url for the image in "backgroundimage"
## you can set a Dark/Light theme for header or navbar. Default: Dark;
backgroundImage:
headerTheme:
navbarTheme:

# menu
nav:
  Home: /.
  Archive: /archives
  About: //yangteng.me

# if you want to change default styles, please install hexo-renderer-less.
# Less
less:
  paths:
    - source/css
  compress: true
